import React, { useState, useEffect } from 'react';
import { aiApi } from '../../api/aiApi';
import {
  Brain,
  Sparkles,
  RefreshCw,
  AlertTriangle,
  CheckCircle2,
  Info,
  ShieldAlert
} from '../common/Icons';

export function AiInsightsCard({ datasetId, studentId, educationLevel }) {
  const [insightData, setInsightData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const fetchInsight = async () => {
    if (!datasetId || !studentId) return;

    setLoading(true);
    setError('');

    try {
      const res = await aiApi.getAiInsight(datasetId, studentId);
      if (res.success && res.ai_insight) {
        setInsightData(res.ai_insight);
      } else {
        setError('No AI insight generated by the backend.');
      }
    } catch (err) {
      console.warn('AI insight error:', err);
      setError(
        err.message || 'Groq AI insight could not be fetched. Check GROQ_API_KEY configuration.'
      );
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchInsight();
  }, [datasetId, studentId]);

  return (
    <div className="ai-insight-card">
      <div className="card-header-row">
        <div className="ai-header-title-box">
          <div className="icon-circle bg-purple-soft text-purple">
            <Sparkles className="w-5 h-5" />
          </div>
          <div>
            <h3 className="card-title">Groq AI Academic Guidance & Insights</h3>
            <p className="card-subtitle">
              Qualitative pedagogical analysis calibrated for{' '}
              <strong>{educationLevel || 'Undergraduate'}</strong> level students.
            </p>
          </div>
        </div>

        <div className="ai-header-actions">
          <button
            type="button"
            className="btn btn-sm btn-outline-purple"
            onClick={fetchInsight}
            disabled={loading}
          >
            <RefreshCw className={`w-3.5 h-3.5 mr-1.5 ${loading ? 'animate-spin' : ''}`} />
            <span>Regenerate Insights</span>
          </button>
        </div>
      </div>

      {/* Authoritative Model Hierarchy Banner */}
      <div className="ai-hierarchy-notice">
        <ShieldAlert className="w-4 h-4 text-purple flex-shrink-0" />
        <p>
          <strong>Decision-Support Notice:</strong> The XGBoost machine learning prediction is authoritative.
          This AI module generates qualitative advisory support and does not alter the calibrated risk probability.
        </p>
      </div>

      {/* Loading state */}
      {loading && (
        <div className="ai-loading-state">
          <RefreshCw className="w-8 h-8 text-purple animate-spin mb-3" />
          <p className="font-semibold text-dark">Synthesizing Pedagogical Guidance...</p>
          <p className="text-muted text-sm">
            Evaluating SHAP factors, intervention policy rules, and education-stage context via Groq LLM.
          </p>
        </div>
      )}

      {/* Error state */}
      {!loading && error && (
        <div className="alert-box alert-warning m-4">
          <AlertTriangle className="w-5 h-5 flex-shrink-0" />
          <div className="alert-content">
            <strong>AI Service Notice:</strong>
            <p>{error}</p>
            <p className="text-xs text-muted mt-1">
              Note: The quantitative XGBoost risk prediction, SHAP values, and Intervention Policy Engine
              remain fully operational above.
            </p>
          </div>
        </div>
      )}

      {/* Main Content */}
      {!loading && !error && insightData && (
        <div className="ai-insight-content">
          {/* Executive Summary */}
          <div className="ai-summary-box">
            <h4 className="ai-section-title">Academic Executive Summary</h4>
            <p className="ai-summary-text">{insightData.summary}</p>
          </div>

          <div className="ai-two-col-grid">
            {/* Key Factors Analysis */}
            <div className="ai-sub-card">
              <h4 className="ai-section-title">Critical Factor Interpretation</h4>
              <div className="ai-factors-list">
                {insightData.key_factors &&
                  insightData.key_factors.map((kf, i) => (
                    <div key={i} className="ai-factor-item">
                      <div className="ai-factor-header">
                        <span className="ai-factor-name">{kf.factor}</span>
                        <span className="ai-factor-contribution">
                          SHAP: {Number(kf.contribution).toFixed(3)}
                        </span>
                      </div>
                      <p className="ai-factor-desc">{kf.interpretation}</p>
                    </div>
                  ))}
              </div>
            </div>

            {/* Practical Faculty Actions */}
            <div className="ai-sub-card">
              <h4 className="ai-section-title">Recommended Faculty Action Items</h4>
              <div className="ai-actions-list">
                {insightData.faculty_actions &&
                  insightData.faculty_actions.map((fa, i) => (
                    <div key={i} className="ai-action-item">
                      <span
                        className={`priority-chip ${
                          (fa.priority || '').toLowerCase() === 'high'
                            ? 'chip-danger'
                            : 'chip-warning'
                        }`}
                      >
                        {fa.priority}
                      </span>
                      <p className="ai-action-desc">{fa.action}</p>
                    </div>
                  ))}
              </div>
            </div>
          </div>

          <div className="ai-two-col-grid mt-4">
            {/* Student Support Suggestions */}
            <div className="ai-sub-card">
              <h4 className="ai-section-title">Personalized Student Support</h4>
              <ul className="ai-bullet-list">
                {insightData.student_support &&
                  insightData.student_support.map((ss, i) => (
                    <li key={i}>
                      <span className="bullet-dot" />
                      <span>{ss}</span>
                    </li>
                  ))}
              </ul>
            </div>

            {/* What to Monitor */}
            <div className="ai-sub-card">
              <h4 className="ai-section-title">Monitoring Checklist for Faculty</h4>
              <ul className="ai-bullet-list">
                {insightData.what_to_monitor &&
                  insightData.what_to_monitor.map((wm, i) => (
                    <li key={i}>
                      <span className="bullet-dot bullet-purple" />
                      <span>{wm}</span>
                    </li>
                  ))}
              </ul>
            </div>
          </div>

          {/* AI Disclaimer */}
          {insightData.disclaimer && (
            <div className="ai-disclaimer-footer">
              <Info className="w-3.5 h-3.5 text-muted mr-1.5 flex-shrink-0" />
              <span>{insightData.disclaimer}</span>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
